### PR TITLE
Calculation tempbasal on the base of avg 30-min basal

### PR DESCRIPTION
**Pull request by infoneo**
https://github.com/openaps/openaps-js/issues/5 Fix

### CODE REVIEW

**Comment by scottleibrand** [comment]
I see you're doing a weighted average of the current and next basal, which looks good (modulo variable misspellings). I don't see why you're eliminating the 2 \* though. That is for converting the units required over 30m into an hourly rate.

**Comment by infoneo** [comment]
You have right. I though, that temp basal is an absolute value, not u/h. I have to correct the function - double result of ThirtyMinBasalFromNow() also.

**Comment by scottleibrand** [comment]
Can you rebase and resubmit this so we can merge it without conflicts?

**Comment by scottleibrand** [comment]
@infoneo are you still interested in rebasing this and getting it merged?  If not, feel free to close it (and issue #5) out.

**Pull request closed without merging**
