### PR TITLE
[add_mit_license] Add MIT License text

### PR DESCRIPTION
**Pull request by oskarpearson**
The "package.json" file indicated that this repository is under MIT license,
Copyright Scott Leibrand. However, this wasn't clearly visible in the source
code, and there was no accompanying license text.

I've added copyright notices and licenses to each file, along with a disclaimer.

If any item here is not under MIT copyright, or under the copyright of someone
other than Scott Leibrand, please let us know. We will rectify the issue
as soon as possible.

Additional changes:
- Removed a large number of commented-out items from dnsmasq.conf, so that
  there's no ambiquity about copyright. The commented-out items are documentation
  from the dnsmasq project, which is released under GPL. See
  http://www.thekelleys.org.uk/dnsmasq/doc.html

### CODE REVIEW

**Comment by scottleibrand** [comment]
Looks good. The only one that I didn't write was sendtempbasal-Azure.js - that one was @amazaheri, so the copyright for that one should either reference him directly, or maybe "OpenAPS contributors" or something.

**Comment by amazaheri** [comment]
In general it would be great to include names, as @scottleibrand  mentioned I wrote sendtempbasal-azure.js and getprofile.js and also initial changes to iob.js and determine-basal.js to remove hard coded values and use getprofile.js output to fill out the blank. But since the whole team is contributing and sending PR (couple of us for now, and hopefully more soon) I like the "OpenAPS Contributors" vs individual names.

**Comment by scottleibrand** [comment]
Ok, yeah, I like using "OpenAPS contributors" for everything. 

-Scott

On Sat, Sep 5, 2015 at 10:10 AM -0700, "Ali Mazaheri" notifications@github.com wrote:

In general it would be great to include names, as @scottleibrand  mentioned I wrote sendtempbasal-azure.js and getprofile.js and also initial changes to iob.js and determine-basal.js to remove hard coded values and use getprofile.js output to fill out the blank. But since the whole team is contributing and sending PR (couple of us for now, and hopefully more soon) I like the "OpenAPS Contributors" vs individual names.

**Comment by oskarpearson** [comment]
Adjusted!

**Pull request merged**
